### ISSUE TITLE
Questions about the new scriban functionalities

### ISSUE THREAD

**Issue by ansari007** [AdamNaj/SitecoreScriban-vscode#1]
Hello @AdamNaj , is there a way where I can utilize the new SXA functionalities in SXA 9?
and regarding the VSC extension, is there a way where I can indent the scriban syntax (formatter) to make it easy to read?
Thanks in advance

**Comment by alan-null** [comment]
@ansari007 
1. Scriban templates are available in [SXA 9.3](https://dev.sitecore.net/Downloads/Sitecore%20Experience%20Accelerator/9x/Sitecore%20Experience%20Accelerator%20930/Release%20Notes) and newer.
There is no way to use it on older versions of SXA.
You could try to port changes from new version to older (there is a separate project for Scriban - code, configs) but I am not sure if there are no breaking changes. SXA upgrade will be easier :) 
2. There is no auto-format for now in the extension
